name: Quarto Render

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: quarto-render
  cancel-in-progress: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0       # needed for rebase
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: quarto render

      - name: Commit & push /docs
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # stage all generated changes (new + modified)
          git add -A docs
          git commit -m "Render site" || echo "No changes to commit"

          # if the branch moved while we rendered, rebase safely
          git fetch origin "$BRANCH"
          git pull --rebase --autostash origin "$BRANCH"
          git push origin HEAD:"$BRANCH"
